spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/driver-api
    username: admin
    password: admin
springdoc:
  api-docs:
    enabled: true
logging:
  level:
    org.springdoc: DEBUG
